TODO_Project_ASP/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using TODO_Project_ASP.Models;
using TODO_Project_ASP.Services;

namespace TODO_Project_ASP.Controllers
{
    public class TasksController : Controller
    {
        // Get: /Tasks/CreateInProject
        [System.Web.Mvc.HttpGet]
        public ViewResult CreateInProject()
        {
            // wird im Overview inkludiert
            return View();
        }

        [System.Web.Mvc.HttpPost]
        // Post: /Tasks/Create
        public ActionResult Create([FromBody] TaskModel taskModel)
        {
            taskModel.ProjectID = ProjectService.getInstance().CurrentProject.ID;
            taskModel.AssigneeID = UserService.getInstance().CurrentUser.ID;
            taskModel.AuthorID = UserService.getInstance().CurrentUser.ID;

            taskModel.CreatedAt = DateTime.Now;


            using (var context = new ApplicationDbContext())
            {
                context.TaskModels.Add(taskModel);
                context.SaveChanges();

                return RedirectToAction("Overview", "Project", ProjectService.getInstance().CurrentProject);
            }
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult UpdateState(TaskModel taskModel)
        {
            var id = taskModel.ID;
            var state = taskModel.State;
            using (var context = new ApplicationDbContext())
            {
                var dbmodel = context.TaskModels.SingleOrDefault((model) => model.ID == id);
                dbmodel.State = state;
                context.SaveChanges();
            }
            return Json(taskModel);
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult UpdateTag(UpdateTagModel model)
        {
            var context = new ApplicationDbContext();
           
            var task = context.TaskModels.SingleOrDefault(m => m.ID == model.TaskID);
            task.TagID = model.TagID;

            context.SaveChanges();

            return Json(true);
        }

        [System.Web.Mvc.HttpGet]
        public ActionResult Single(TaskModel taskModel)
        {
            Debug.WriteLine("single task");
            Debug.WriteLine(taskModel.ID);
            var context = new ApplicationDbContext();

            taskModel = context.TaskModels.Find(taskModel.ID);

           
            var jsonData = new TaskDetailsViewModel()
            {
                ID = taskModel.ID,
                Name = taskModel.Name,
                Description = taskModel.Description,
                FormattedCreatedAt = taskModel.CreatedAt.ToShortDateString(),
                FormattedDueTo = taskModel.DueTo.ToShortDateString(),
                AuthorName =  taskModel.Author.Name,
                AsigneeName = taskModel.Assignee.Name,
                TagName = (taskModel.Tag == null) ? "Noch kein Tag" : taskModel.Tag.Name
               // State = taskModel.State
            };

            return Json(jsonData, JsonRequestBehavior.AllowGet);
        } 


    }
}

TODO_Project_ASP/Views/Tasks/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

TODO_Project_ASP/Views/Tasks/CreateInProject.cshtml
@using TODO_Project_ASP.Models
@model TODO_Project_ASP.Models.TaskModel


@using (Html.BeginForm("Create", "Tasks", FormMethod.Post))
{
<div class="modal fade" id="modal-task-create">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Neuen Task erstellen</h4>
            </div>
            <div class="modal-body">
                    @Html.AntiForgeryToken()
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label left-align col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        @Html.HiddenFor(model => model.CreatedAt, DateTime.Now.ToShortDateString())

                        <div class="form-group">
                            @Html.LabelFor(model => model.DueTo, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.DueTo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DueTo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Erstellen</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Abbrechen</button>
            </div>
        </div>
    </div>
</div>
}

TODO_Project_ASP/Views/Tasks/Details.cshtml
<div class="modal fade" id="modal-task-details">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <div id="modal-task-details-tag">
                    Noch kein Tag
                </div>
                <h4 class="modal-title" id="modal-task-details-title"></h4>
                <div id="modal-task-details-author"></div>
            </div>
            <div class="modal-body">
                <p id="modal-task-details-description"></p>
                <div class="modal-task-details-assignee-information">
                    <div id="modal-task-details-assignee"></div>
                    <div id="modal-task-details-due-to"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="select-tag-container hidden">
    <div class="select-tag-tag create-tag">
        @Html.TextBox("tag-name")
    </div>
</div>

<div class="create-tag-container">
    
</div>

TODO_Project_ASP/Views/Tasks/List.cshtml
@model IEnumerable<TODO_Project_ASP.Models.TaskModel>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DueTo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedAt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DueTo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

TODO_Project_ASP/Views/Tasks/Single.cshtml
@model TODO_Project_ASP.Models.TaskModel

@{
    ViewBag.Title = "Single";
}

<div class="single-task-container" draggable="true" ondragstart="window.tododrag(event)" 
     onclick="window.showTaskDetailModal(@Html.DisplayFor(model => model.ID))" data-id="@Html.DisplayFor(model => model.ID)"
     id="single-task-container-@Html.DisplayFor(model => model.ID)">
    <div class="single-task-name">
        @Html.DisplayFor(model => model.Name)
    </div>
</div>